module.exports = [{"name": "append"},
{"name":"ADD"},
{"name":"AUTH"},
{"name":"BGREWRITEAOF"},
{"name":"BGSAVE"},
{"name":"CLUSTER"},
{"name":"GET  key"},
{"name":"HGET key field"},
{"name":"HGETALL key"},
{"name":"SADD key member [member ...]"},
{"name":"SET key value [EX seconds] [PX milliseconds] [NX|XX]"},
{"name":"SMEMBERS key"},
{"name":"ZADD key [NX|XX] [CH] [INCR] score member [score member ...]"},
{"name":"ZCARD key"},
{"name":"ZCOUNT key min max"},
{"name":"ZINCRBY key increment member"},
{"name":"ZINTERSTORE destination numkeys key [key ...] [WEIGHTS weight [weight ...]] [AGGREGATE SUM|MIN|MAX]"},
{"name":"ZLEXCOUNT key min max"},
{"name":"ZRANGE key start stop [WITHSCORES]"},
{"name":"ZRANGEBYLEX key min max [LIMIT offset count]"},
{"name":"ZREVRANGEBYLEX key max min [LIMIT offset count]"},
{"name":"ZRANGEBYSCORE key min max [WITHSCORES] [LIMIT offset count]"},

]